<?php
/**
 * Zigbee2Mqtt service configuration
 */
class ServiceConfig {

    /**
     * Path to the zigbee device
     * @var string */
    public $port = '';

    /**
     * Adapter type
     * @var string
     */
    public $adapter = '';
    /**
     * Serial baudrate. Empty string means: leave the value in
     * configuration.yaml untouched.
     * @var string
     */
    public $baudrate = '';

    /**
     * Serial hardware flow control. Empty string means: leave the value in
     * configuration.yaml untouched; "true" / "false" set it explicitly.
     * @var string
     */
    public $rtscts = '';

    /**
     * Enable zigbee2mqtt ui
     * @var bool
     */
    public $enableUI = false;

    /**
     * Port of the zigbee2mqtt ui
     * @var string
     */
    public $frontendPort = '8881';

    /**
     * Protect the zigbee2mqtt ui with a token (frontend.auth_token)
     * @var bool
     */
    public $frontendAuth = true;

    /**
     * Token of the zigbee2mqtt ui, generated by update-config.php
     * @var string
     */
    public $frontendToken = '';

    /**
     * Zigbee channel (11-26). Empty string means: leave the value in
     * configuration.yaml untouched.
     * @var string
     */
    public $channel = '';

    /**
     * Publish the availability (online/offline) of every device
     * @var bool
     */
    public $availability = true;

    /**
     * LoxBerry notification when a device goes offline
     * @var bool
     */
    public $notifyOffline = true;

    /**
     * LoxBerry notification when a battery runs low
     * @var bool
     */
    public $notifyBattery = true;

    /**
     * Battery level (percent) for the notification
     * @var string
     */
    public $batteryThreshold = '15';

    /**
     * Adapter types zigbee2mqtt accepts (serial.adapter)
     */
    const ADAPTERS = array("zstack", "ember", "deconz", "zigate", "zboss", "zoh", "ezsp");

    /**
     * Creates a new instance
     */
    public function __construct() {
    }


    /**
     * Loads the config. Only known settings are taken over - a setting of an
     * older version (e.g. permitJoin) is dropped on the next save.
     */
    public static function load() {
        $configfile = LBPCONFIGDIR . "/service.json";
        $data = json_decode(@file_get_contents($configfile), true);
        $class = new ServiceConfig();
        foreach ((is_array($data) ? $data : array()) as $key => $value) {
            if (property_exists($class, $key)) {
                $class->{$key} = $value;
            }
        }
        return $class;
    }

    /**
     * Checks the values. Returns a list of language keys of the errors.
     */
    public function validate() {
        $daten = get_object_vars($this);
        $errors = array();
        foreach ($daten as $key => $value) {
            list($ok, $result) = self::wert($key, $value, $daten);
            if (!$ok && !in_array($result, $errors, true)) {
                $errors[] = $result;
            }
        }
        return $errors;
    }

    /**
     * 4.1.1 (B11): checks one value. Returns array(true, normalised value)
     * or array(false, language key of the error). The type is checked
     * before the pattern, every pattern ends with \z; a channel "15.7" or a
     * flow control "maybe" is rejected, not turned into 15 or false.
     */
    public static function wert($key, $value, $daten) {
        switch ($key) {
            case "enableUI":
            case "frontendAuth":
            case "availability":
            case "notifyOffline":
            case "notifyBattery":
                $b = zng_haken($value);
                return $b === null ? array(false, "ServiceConfig.ValSwitch") : array(true, $b);
            case "port":
                $ok = $value === "" || (is_string($value) && preg_match('#^(/dev/[A-Za-z0-9/_.:\-]{1,200}|tcp://[A-Za-z0-9.\-]{1,253}:[0-9]{1,5}|mdns://[A-Za-z0-9.\-]{1,253})\z#', $value));
                return $ok ? array(true, $value) : array(false, "ServiceConfig.ValPort");
            case "adapter":
                return $value === "" || in_array($value, self::ADAPTERS, true) ? array(true, $value) : array(false, "ServiceConfig.ValAdapter");
            case "baudrate":
                if ($value === "") {
                    return array(true, "");
                }
                $baud = zng_zahl_text($value, 100, 9999999, '/^[0-9]{3,7}\z/');
                return $baud === null ? array(false, "ServiceConfig.ValBaudrate") : array(true, $baud);
            case "rtscts":
                // three ways: "" leaves configuration.yaml alone; a true/false
                // of an older version is kept with the same meaning
                if (is_bool($value)) {
                    return array(true, $value ? "true" : "false");
                }
                return in_array($value, array("", "true", "false"), true) ? array(true, $value) : array(false, "ServiceConfig.ValRtscts");
            case "frontendPort":
                $port = zng_zahl_text($value, 1, 65535, '/^[1-9][0-9]{0,4}\z/');
                return $port === null ? array(false, "ServiceConfig.ValFrontendPort") : array(true, $port);
            case "frontendToken":
                return $value === "" || (is_string($value) && preg_match('/^[A-Za-z0-9]{16,64}\z/', $value))
                    ? array(true, $value) : array(false, "ServiceConfig.ValToken");
            case "channel":
                if ($value === "") {
                    return array(true, "");
                }
                $channel = zng_zahl_text($value, 11, 26, '/^(1[1-9]|2[0-6])\z/');
                return $channel === null ? array(false, "ServiceConfig.ValChannel") : array(true, $channel);
            case "batteryThreshold":
                $level = zng_zahl_text($value, 1, 99, '/^[1-9][0-9]?\z/');
                return $level === null ? array(false, "ServiceConfig.ValBattery") : array(true, $level);
        }
        return array(false, "Common.UnknownKey");
    }

    /**
     * 4.1.1 (B1): state of service.json - "fehlt", "ok" or "kaputt"
     */
    public static function lage() {
        return zng_json_lage(LBPCONFIGDIR . "/service.json");
    }

    /**
     * Values that are not part of the form are kept from the saved config
     */
    public function keepFrom(ServiceConfig $saved) {
        $this->frontendToken = $saved->frontendToken;
    }

    /**
     * Saves the config. Returns false if it could not be written (the old
     * file is kept then).
     */
    public function save() {
        // 4.1.1 (B4): in one piece and 0600 (token of the zigbee2mqtt UI);
        // the second copy follows a readable state only
        $configfile = LBPCONFIGDIR . "/service.json";
        if (!zng_schreiben_wenn_anders($configfile, $this->toJson(), ZNG_MODUS_GEHEIM)) {
            return false;
        }
        zng_zweitschrift_ziehen($configfile, "json", LBPCONFIGDIR, "service.json");
        return true;
    }

    /**
     * Creates a json string out of the config
     */
    public function toJson() {
        return json_encode($this, JSON_PRETTY_PRINT);
    }
}
